server.contextPath=/esign-interceptor
server.servlet.context-path=/esign-interceptor
management.endpoints.web.base-path=/
server.port=8080
app.timezone=Asia/Kolkata

#OTEL CONFIGURATION
otel.traces.exporter=otlp
otel.service.name=esign-interceptor
otel.logs.exporter=none
otel.metrics.exporter=none
otel.exporter.otlp.endpoint=http://jaeger-collector.tracing:4318
otel.exporter.otlp.protocol=http/protobuf
otel.instrumentation.kafka.enabled=true
otel.instrumentation.kafka.experimental-span-attributes=true
otel.instrumentation.http.server.ignore-urls=/esign-interceptor/health,/esign-interceptor/prometheus

# File store service
egov.filestore.host=http://localhost:8052/
egov.filestore.search.endpoint=filestore/v1/files/id

drishti.esign.host=http://localhost:8051
drishti.esign.endpoint=/e-sign-svc/v1/_signed


drishti.esign.redirect.url=https://dristi-kerala-dev.pucar.org
drishti.esign.landing.page.redirect.url=/landing

drishti.oath.host=https://dristi-kerala-dev.pucar.org/

drishti.oath.endpoint=user/oauth/token?_=1713357247536

dristhi.oath.username=esigninterceptor

dristhi.oath.password=Beehyv@123

dristhi.oath.tenantId=kl

dristhi.oath.usertype=EMPLOYEE

dristhi.oath.scope=read

dristhi.oath.grantType=password

logging.loki.enabled=false
logging.loki.url=http://localhost:3100/loki/api/v1/push
logging.loki.app=evidence
logging.loki.environment=local
logging.level.root=INFO