export const ORDER_TYPES = {
  NOTICE: "NOTICE",
  SUMMONS: "SUMMONS",
  WARRANT: "WARRANT",
  PROCLAMATION: "PROCLAMATION",
  ATTACHMENT: "ATTACHMENT",
  MISCELLANEOUS_PROCESS: "MISCELLANEOUS_PROCESS",
};

export const ORDER_CATEGORIES = {
  COMPOSITE: "COMPOSITE",
  INTERMEDIATE: "INTERMEDIATE",
};

export const STATUS_TYPES = {
  COMPLETED: "COMPLETED",
  IN_PROGRESS: "IN_PROGRESS",
  PENDING: "PENDING",
  UNDER_SCRUTINY: "UNDER_SCRUTINY",
  PENDING_PAYMENT: "PENDING_PAYMENT",
};

export const ENTITY_TYPES = {
  TASK_MANAGEMENT_PAYMENT: "task-management-payment",
  TASK_MANAGEMENT_ORDER: "task-management-order",
  TASK_MANAGEMENT_HEARING: "task-management-hearing",
};

export const USER_ROLES = {
  CITIZEN: "CITIZEN",
  JUDGE: "JUDGE",
  ADVOCATE: "ADVOCATE",
};
