export const VerifyMultipartyLitigantConfig = [
  {
    body: [
      {
        inline: true,
        label: "FIRST_NAME",
        isMandatory: true,
        key: "firstName",
        type: "text",
        disable: false,
        populators: {
          name: "firstName",
          error: "Required",
          validation: { pattern: /^[A-Za-z]+$/i },
          customStyle: { display: "flex", flexDirection: "column", alignItems: "flex-start" },
        },
      },
      {
        inline: true,
        label: "MIDDLE_NAME",
        isMandatory: false,
        key: "middleName",
        type: "text",
        disable: false,
        labelChildren: "optional",
        populators: { name: "middleName", customStyle: { display: "flex", flexDirection: "column", alignItems: "flex-start" } },
      },
      {
        inline: true,
        label: "LAST_NAME",
        isMandatory: false,
        key: "lastName",
        type: "text",
        disable: false,
        labelChildren: "optional",
        populators: { name: "lastName", customStyle: { display: "flex", flexDirection: "column", alignItems: "flex-start" } },
      },
      {
        type: "component",
        component: "VerifyPhoneNumber",
        key: "phoneNumberVerification",
        withoutLabel: true,
        label: "Mobile No",
        name: "mobileNumber",
        error: "ERR_HRMS_INVALID_MOB_NO",
        componentInFront: "+91",
        disableConfigFields: ["firstName", "middleName", "lastName"],
        requiredFields: ["firstName"],
        confirmModal: true,
        disableConfigKey: "individualDetails",
        isMandatory: true,
        isVerifiedOtpDisabledKey: "isDuplicateNumber",
        screen: "join-case",
        validation: {
          required: true,
          minLength: 10,
          maxLength: 10,
          pattern: /^[6-9]\d{9}$/,
        },
        populators: {},
      },
      {
        key: "isVakalatnamaNew",
        type: "radio",
        label: "IS_VAKALATNAMA_NEW",
        populators: {
          name: "isVakalatnamaNew",
          type: "radioButton",
          error: "CORE_REQUIRED_FIELD_ERROR",
          label: "IS_VAKALATNAMA_NEW",
          options: [
            {
              code: "YES",
              name: "YES",
            },
            {
              code: "NO",
              name: "NO",
            },
          ],
          required: true,
          optionsKey: "name",
          isDependent: true,
          isMandatory: true,
        },
        isMandatory: true,
      },
      {
        type: "text",
        label: "NUMBER_OF_ADVOCATES_FOR_THIS_VAKALATNAMA",
        key: "noOfAdvocates",
        populators: {
          name: "noOfAdvocates",
          error: "NUMBER_OF_ADVOCATES_FOR_THIS_VAKALATNAMA_ERROR",
          validation: {
            maxLength: 3,
            patternType: "Number",
          },
        },
        isMandatory: true,
      },
      {
        type: "component",
        component: "SelectCustomDragDrop",
        key: "vakalatnama",
        isMandatory: true,
        withoutLabel: true,
        populators: {
          inputs: [
            {
              name: "document",
              documentHeader: "Vakalatnama",
              type: "DragDropComponent",
              uploadGuidelines: "UPLOAD_DOC_10",
              maxFileSize: 10,
              maxFileErrorMessage: "CS_FILE_LIMIT_10_MB",
              fileTypes: ["JPG", "PDF", "PNG", "JPEG"],
              isMultipleUpload: false,
            },
          ],
        },
      },
    ],
  },
];

export const VerifyPoaClaiming = [
  {
    body: [
      {
        inline: true,
        label: "FIRST_NAME",
        isMandatory: true,
        key: "firstName",
        type: "text",
        disable: false,
        populators: {
          name: "firstName",
          error: "Required",
          validation: { pattern: /^[A-Za-z]+$/i },
          customStyle: { display: "flex", flexDirection: "column", alignItems: "flex-start" },
        },
      },
      {
        inline: true,
        label: "MIDDLE_NAME",
        isMandatory: false,
        key: "middleName",
        type: "text",
        disable: false,
        labelChildren: "optional",
        populators: { name: "middleName", customStyle: { display: "flex", flexDirection: "column", alignItems: "flex-start" } },
      },
      {
        inline: true,
        label: "LAST_NAME",
        isMandatory: false,
        key: "lastName",
        type: "text",
        disable: false,
        labelChildren: "optional",
        populators: { name: "lastName", customStyle: { display: "flex", flexDirection: "column", alignItems: "flex-start" } },
      },
      {
        type: "component",
        component: "VerifyPhoneNumber",
        key: "phoneNumberVerification",
        withoutLabel: true,
        label: "Mobile No",
        name: "mobileNumber",
        error: "ERR_HRMS_INVALID_MOB_NO",
        componentInFront: "+91",
        disableConfigFields: ["firstName", "middleName", "lastName"],
        requiredFields: ["firstName"],
        confirmModal: true,
        disableConfigKey: "individualDetails",
        isMandatory: true,
        isVerifiedOtpDisabledKey: "isDuplicateNumber",
        screen: "join-case",
        validation: {
          required: true,
          minLength: 10,
          maxLength: 10,
          pattern: /^[6-9]\d{9}$/,
        },
        populators: {},
      },
      {
        type: "component",
        component: "SelectCustomNote",
        key: "poaCustomInfo",
        withoutLabel: true,
        populators: {
          inputs: [
            {
              infoHeader: "CS_COMMON_NOTE",
              infoText: "POA_CLAIMING_INFO_TEXT",
              type: "InfoComponent",
              showTooltip: true,
            },
          ],
        },
      },
      {
        type: "component",
        component: "SelectCustomDragDrop",
        key: "poaAuthorizationDocument",
        isMandatory: true,
        withoutLabel: true,
        populators: {
          inputs: [
            {
              name: "poaDocument",
              documentHeader: "POA_AUTHORIZATION_DOCUMENT",
              type: "DragDropComponent",
              uploadGuidelines: "UPLOAD_DOC_10",
              maxFileSize: 10,
              maxFileErrorMessage: "CS_FILE_LIMIT_10_MB",
              fileTypes: ["JPG", "PDF", "PNG", "JPEG"],
              isMultipleUpload: true,
              documentDescription: "POA_AUTHORIZATION_DOCUMENT_DESCRIPTION",
            },
          ],
        },
      },
    ],
  },
];
