export const OrderTypes = { SCHEDULE_OF_HEARING_DATE: "SCHEDULE_OF_HEARING_DATE" };

export const OrderWorkflowState = {
  ABATED: "ABATED",
  DRAFT_IN_PROGRESS: "DRAFT_IN_PROGRESS",
  PENDING_BULK_E_SIGN: "PENDING_BULK_E-SIGN",
  PUBLISHED: "PUBLISHED",
  DELETED: "DELETED",
  PENDING_E_SIGN: "PENDING_E-SIGN",
};

export const OrderWorkflowAction = {
  SAVE_DRAFT: "SAVE_DRAFT",
  ESIGN: "E-SIGN",
  DELETE: "DELETE",
  ABANDON: "ABANDON",
};

export const MediationWorkflowAction = {
  INITIATE_E_SIGN: "INITIATE_E-SIGN",
  INITIATE_UPLOAD: "INITIATE_UPLOAD",
  DELETE_DRAFT: "DELETE_DRAFT",
  SKIP_SIGN_AND_SUBMIT: "SKIP_SIGN_AND_SUBMIT",
  EDIT: "EDIT",
  SIGN: "SIGN",
  UPLOAD: "UPLOAD",
  E_SIGN: "E-SIGN",
  E_SIGN_COMPLETE: "E-SIGN_COMPLETE",
};

export const MediationWorkflowState = {
  DRAFT_IN_PROGRESS: "DRAFT_IN_PROGRESS",
  PENDING_E_SIGN: "PENDING_E-SIGN",
  PENDING_UPLOAD: "PENDING_UPLOAD",
  PENDING_REVIEW: "PENDING_REVIEW",
  DELETED_DRAFT: "DELETED_DRAFT",
  COMPLETED: "COMPLETED",
};
