export const OrderTypes = { SCHEDULE_OF_HEARING_DATE: "SCHEDULE_OF_HEARING_DATE" };

export const OrderWorkflowState = {
  ABATED: "ABATED",
  DRAFT_IN_PROGRESS: "DRAFT_IN_PROGRESS",
  PENDING_BULK_E_SIGN: "PENDING_BULK_E-SIGN",
  PUBLISHED: "PUBLISHED",
  DELETED: "DELETED",
  PENDING_E_SIGN: "PENDING_E-SIGN",
};

export const OrderWorkflowAction = {
  SAVE_DRAFT: "SAVE_DRAFT",
  ESIGN: "E-SIGN",
  DELETE: "DELETE",
  ABANDON: "ABANDON",
};
