export const SubmissionWorkflowAction = {
  CREATE: "CREATE",
  ESIGN: "E-SIGN",
  RESPOND: "RESPOND",
  REJECT: "REJECT",
  ABANDON: "ABANDON",
  APPROVE: "APPROVE",
  DELETE: "DELETE",
};
export const SubmissionWorkflowState = {
  PENDINGSUBMISSION: "PENDING_E-SIGN",
  PENDINGPAYMENT: "PENDING_PAYMENT",
  PENDINGESIGN: "PENDING_E-SIGN",
  PENDINGREVIEW: "PENDING_REVIEW",
  PENDINGAPPROVAL: "PENDING_APPROVAL",
  PENDINGRESPONSE: "PENDINGRESPONSE",
  COMPLETED: "COMPLETED",
  DELETED: "DELETED",
  ABATED: "ABATED",
  REJECTED: "REJECTED",
  DOC_UPLOAD: "DOCUMENT_UPLOAD",
};

export const SubmissionDocumentsWorkflowState = {
  PENDING_ESIGN: "PENDING_E-SIGN",
  SUBMITTED: "SUBMITTED",
};
