export const SubmissionWorkflowAction = {
  CREATE: "CREATE",
  ESIGN: "ESIGN",
  RESPOND: "RESPOND",
  REJECT: "REJECT",
  ABANDON: "ABANDON",
  APPROVE: "APPROVE",
  DELETE: "DELETE",
  PAY: "PAY",
};
export const SubmissionWorkflowState = {
  PENDINGSUBMISSION: "PENDINGSUBMISSION",
  PENDINGPAYMENT: "PENDINGPAYMENT",
  PENDINGESIGN: "PENDINGESIGN",
  PENDINGREVIEW: "PENDINGREVIEW",
  PENDINGAPPROVAL: "PENDINGAPPROVAL",
  PENDINGRESPONSE: "PENDINGRESPONSE",
  COMPLETED: "COMPLETED",
  DELETED: "DELETED",
  ABATED: "ABATED",
  REJECTED: "REJECTED",
  DOC_UPLOAD: "DOCUMENT_UPLOAD",
};

export const SubmissionDocumentsWorkflowState = {
  PENDING_ESIGN: "PENDING_E-SIGN",
  SUBMITTED: "SUBMITTED",
};

export const bailBondWorkflowAction = {
  SAVEDRAFT: "SAVE_DRAFT",
  INITIATEESIGN: "INITIATE_E-SIGN",
  UPLOAD: "UPLOAD",
  EDIT: "EDIT",
  ESIGN: "E-SIGN",
  SIGN: "SIGN",
  REJECT: "REJECT",
};

export const witnessDepositionWorkflowAction = {
  SAVEDRAFT: "SAVE_DRAFT",
  INITIATEESIGN: "INITIATE_E-SIGN",
  UPLOAD: "UPLOAD",
  EDIT: "EDIT",
  ESIGN: "E-SIGN",
  SIGN: "SIGN",
  REJECT: "REJECT",
};

export const MarkAsEvidenceAction = {
  CREATE: "CREATE",
  SAVEDRAFT: "SAVE_DRAFT",
  ESIGN: "E-SIGN",
  BULKSIGN: "SUBMIT_BULK_E-SIGN",
  EDIT: "EDIT",
};
