export const APPLICATION_TYPES = {
  DELAY_CONDONATION: "DELAY_CONDONATION",
  EXTENSION_SUBMISSION_DEADLINE: "EXTENSION_SUBMISSION_DEADLINE",
  PRODUCTION_DOCUMENTS: "PRODUCTION_DOCUMENTS",
  SUBMIT_BAIL_DOCUMENTS: "SUBMIT_BAIL_DOCUMENTS",
};

export const STATUS_TYPES = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUBMITTED: "SUBMITTED",
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
};

export const ORDER_TYPES = {
  NOTICE: "NOTICE",
  SUMMONS: "SUMMONS",
  WARRANT: "WARRANT",
  PROCLAMATION: "PROCLAMATION",
  ATTACHMENT: "ATTACHMENT",
  MISCELLANEOUS_PROCESS: "MISCELLANEOUS_PROCESS",
};

export const ORDER_CATEGORIES = {
  COMPOSITE: "COMPOSITE",
  SINGLE: "SINGLE",
};
