server
{
  listen 80;
  underscores_in_headers on;

  location /ui
  {
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
      add_header Cache-Control "public, max-age=86400";
    }
    
    root /var/web;
    index index.html index.htm;
    try_files $uri $uri/ /ui/index.html;
  }
}