export const optionsStatus = ["PENDING_RESPONSE", "ADMISSION_HEARING_SCHEDULED", "CASE_ADMITTED", "PENDING_ADMISSION"];

export const JoinHomeLocalisation = {
  ADVOCATE_OPT: "ADVOCATE_OPT",
  LITIGANT_OPT: "LITIGANT_OPT",
  COMPLAINANT_BRACK: "COMPLAINANT_BRACK",
  RESPONDENT_BRACK: "RESPONDENT_BRACK",
  CASE_NOT_ADMITTED_TEXT: "CASE_NOT_ADMITTED_TEXT",
  JOIN_CASE_BACK_TEXT: "JOIN_CASE_BACK_TEXT",
  INVALID_ACCESS_CODE_MESSAGE: "INVALID_ACCESS_CODE_MESSAGE",
  JOIN_CASE_SUCCESS: "JOIN_CASE_SUCCESS",
  APPLICATION_CREATION_FAILED: "APPLICATION_CREATION_FAILED",
};

export const STATUS_TYPES = {
  PENDING_RESPONSE: "PENDING_RESPONSE",
  ADMISSION_HEARING_SCHEDULED: "ADMISSION_HEARING_SCHEDULED",
  CASE_ADMITTED: "CASE_ADMITTED",
  PENDING_ADMISSION: "PENDING_ADMISSION",
  COMPLETED: "COMPLETED",
  IN_PROGRESS: "IN_PROGRESS",
  ABATED: "ABATED",
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const ORDER_TYPES = {
  NOTICE: "NOTICE",
  SUMMONS: "SUMMONS",
  WARRANT: "WARRANT",
};

export const HEARING_TYPES = {
  ADMISSION: "ADMISSION",
  REGULAR: "REGULAR",
  MENTIONING: "MENTIONING",
};

export const ORDER_CATEGORIES = {
  COMPOSITE: "COMPOSITE",
  SINGLE: "SINGLE",
};
