server.port=8089
server.context-path=/otp
server.servlet.context-path=/otp
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database=postgresql
spring.datasource.url=${db.url:jdbc:postgresql://localhost:5432/newdb}
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.outOfOrder=true
spring.flyway.baseline-on-migrate=true
spring.flyway.url=jdbc:postgresql://localhost:5432/newdb
spring.flyway.locations=classpath:/db/migration/main

app.timezone=UTC

management.endpoints.web.base-path=/

egov.otp.length=6
egov.otp.ttl=900
egov.otp.encrypt=true

#OTEL CONFIGURATION
otel.traces.exporter=otlp
otel.service.name=egov-otp
otel.logs.exporter=none
otel.metrics.exporter=none
otel.exporter.otlp.endpoint=http://jaeger-collector.tracing:4318
otel.exporter.otlp.protocol=http/protobuf
otel.instrumentation.kafka.enabled=true
otel.instrumentation.kafka.experimental-span-attributes=true
otel.instrumentation.http.server.ignore-urls=/otp/health,/otp/prometheus

