server.servlet.context-path=/bank-details
server.port=8080
razorpay.ifsc.api=https://ifsc.razorpay.com/
razorpay.ifsc.connect-timeout=3000
razorpay.ifsc.read-timeout=5000

#OTEL CONFIGURATION
otel.traces.exporter=otlp
otel.service.name=bank-details
otel.logs.exporter=none
otel.metrics.exporter=none
otel.exporter.otlp.endpoint=http://jaeger-collector.tracing:4318
otel.exporter.otlp.protocol=http/protobuf
otel.instrumentation.kafka.enabled=true
otel.instrumentation.kafka.experimental-span-attributes=true
otel.instrumentation.http.server.ignore-urls=/bank-details/health,/bank-details/prometheus

