server.servlet.context-path=/bank-details
server.port=8080
razorpay.ifsc.api=https://ifsc.razorpay.com/
razorpay.ifsc.connect-timeout=3000
razorpay.ifsc.read-timeout=5000

#OTEL CONFIGURATION
otel.service.name=bank-details
otel.instrumentation.http.server.ignore-urls=/bank-details/health,/bank-details/prometheus

