export const ORDER_TYPES = {
  NOTICE: "NOTICE",
  SUMMONS: "SUMMONS",
  WARRANT: "WARRANT",
  PROCLAMATION: "PROCLAMATION",
  ATTACHMENT: "ATTACHMENT",
  MISCELLANEOUS_PROCESS: "MISCELLANEOUS_PROCESS",
};

export const TASK_TYPES = {
  NOTICE: "NOTICE",
  SUMMONS: "SUMMONS",
  WARRANT: "WARRANT",
};

export const CHANNEL_IDS = {
  RPAD: "RPAD",
  POLICE: "POLICE",
};

export const ORDER_CATEGORIES = {
  COMPOSITE: "COMPOSITE",
  INTERMEDIATE: "INTERMEDIATE",
};

export const STATUS_TYPES = {
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  DRAFT: "DRAFT",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  IN_PROGRESS: "IN_PROGRESS",
  ABATED: "ABATED",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  UNDER_SCRUTINY: "UNDER_SCRUTINY",
  CASE_ADMITTED: "CASE_ADMITTED",
  CASE_DISMISSED: "CASE_DISMISSED",
};

export const DELIVERY_CHANNELS = {
  POLICE: "Police",
  RPAD: "RPAD",
};
