/**
 * Constants and configurations for orders module
 */

// Import all config files
import {
  configsOrderSection202CRPC,
  configsOrderMandatorySubmissions,
  configsOrderSubmissionExtension,
  configsOrderTranferToADR,
  configsScheduleHearingDate,
  configsScheduleNextHearingDate,
  configsRescheduleHearingDate,
  configCheckout,
  configsRejectCheckout,
  configsRejectRescheduleHeadingDate,
  configsInitiateRescheduleHearingDate,
  configsAssignDateToRescheduledHearing,
  configsAssignNewHearingDate,
  configsCaseTransferAccept,
  configsCaseTransferReject,
  configsCaseSettlementAccept,
  configsCaseSettlementReject,
  configsIssueSummons,
  configsIssueNotice,
  configsBail,
  configsCreateOrderWarrant,
  configsCreateOrderProclamation,
  configsCreateOrderAttachment,
  configsCaseWithdrawalAccept,
  configsCaseWithdrawalReject,
  configsOthers,
  configsVoluntarySubmissionStatus,
  configRejectSubmission,
  configsJudgement,
  configsIssueBailReject,
  configsIssueBailAcceptance,
  configsSetTermBail,
  configsAcceptRejectDelayCondonation,
  configsAdmitCase,
  configsDismissCase,
  configsApproveRejectLitigantDetailsChange,
  replaceAdvocateConfig,
  configsMoveCaseToLongPendingRegister,
  configsMoveCaseOutOfLongPendingRegister,
  configsCost,
  configsWitnessBatta,
  configsAbateCase,
  configAcceptReschedulingRequest,
  configMiscellaneousProcess,
} from "../configs/ordersCreateConfig";

/**
 * Mapping of order types to their respective configurations
 */
export const configKeys = {
  SECTION_202_CRPC: configsOrderSection202CRPC,
  MANDATORY_SUBMISSIONS_RESPONSES: configsOrderMandatorySubmissions,
  EXTENSION_OF_DOCUMENT_SUBMISSION_DATE: configsOrderSubmissionExtension,
  REFERRAL_CASE_TO_ADR: configsOrderTranferToADR,
  SCHEDULE_OF_HEARING_DATE: configsScheduleHearingDate,
  SCHEDULING_NEXT_HEARING: configsScheduleNextHearingDate,
  RESCHEDULE_OF_HEARING_DATE: configsRescheduleHearingDate,
  CHECKOUT_ACCEPTANCE: configCheckout,
  CHECKOUT_REJECT: configsRejectCheckout,
  REJECTION_RESCHEDULE_REQUEST: configsRejectRescheduleHeadingDate,
  INITIATING_RESCHEDULING_OF_HEARING_DATE: configsInitiateRescheduleHearingDate,
  ASSIGNING_DATE_RESCHEDULED_HEARING: configsAssignDateToRescheduledHearing,
  ASSIGNING_NEW_HEARING_DATE: configsAssignNewHearingDate,
  CASE_TRANSFER_ACCEPT: configsCaseTransferAccept,
  CASE_TRANSFER_REJECT: configsCaseTransferReject,
  SETTLEMENT_ACCEPT: configsCaseSettlementAccept,
  SETTLEMENT_REJECT: configsCaseSettlementReject,
  SUMMONS: configsIssueSummons,
  NOTICE: configsIssueNotice,
  BAIL: configsBail,
  WARRANT: configsCreateOrderWarrant,
  PROCLAMATION: configsCreateOrderProclamation,
  ATTACHMENT: configsCreateOrderAttachment,
  WITHDRAWAL_ACCEPT: configsCaseWithdrawalAccept,
  WITHDRAWAL_REJECT: configsCaseWithdrawalReject,
  OTHERS: configsOthers,
  APPROVE_VOLUNTARY_SUBMISSIONS: configsVoluntarySubmissionStatus,
  REJECT_VOLUNTARY_SUBMISSIONS: configRejectSubmission,
  JUDGEMENT: configsJudgement,
  REJECT_BAIL: configsIssueBailReject,
  ACCEPT_BAIL: configsIssueBailAcceptance,
  SET_BAIL_TERMS: configsSetTermBail,
  ACCEPTANCE_REJECTION_DCA: configsAcceptRejectDelayCondonation,
  TAKE_COGNIZANCE: configsAdmitCase,
  DISMISS_CASE: configsDismissCase,
  APPROVAL_REJECTION_LITIGANT_DETAILS_CHANGE: configsApproveRejectLitigantDetailsChange,
  ADVOCATE_REPLACEMENT_APPROVAL: replaceAdvocateConfig,
  MOVE_CASE_TO_LONG_PENDING_REGISTER: configsMoveCaseToLongPendingRegister,
  MOVE_CASE_OUT_OF_LONG_PENDING_REGISTER: configsMoveCaseOutOfLongPendingRegister,
  COST: configsCost,
  WITNESS_BATTA: configsWitnessBatta,
  ABATE_CASE: configsAbateCase,
  ACCEPT_RESCHEDULING_REQUEST: configAcceptReschedulingRequest,
  MISCELLANEOUS_PROCESS: configMiscellaneousProcess,
};

/**
 * State SLA mapping for different order types (in days)
 */
export const stateSlaMap = {
  SECTION_202_CRPC: 3,
  MANDATORY_SUBMISSIONS_RESPONSES: 3,
  EXTENSION_OF_DOCUMENT_SUBMISSION_DATE: 3,
  REFERRAL_CASE_TO_ADR: 3,
  SCHEDULE_OF_HEARING_DATE: 3,
  RESCHEDULE_OF_HEARING_DATE: 3,
  REJECTION_RESCHEDULE_REQUEST: 3,
  APPROVAL_RESCHEDULE_REQUEST: 3,
  INITIATING_RESCHEDULING_OF_HEARING_DATE: 1,
  ASSIGNING_DATE_RESCHEDULED_HEARING: 3,
  ASSIGNING_NEW_HEARING_DATE: 3,
  CASE_TRANSFER_ACCEPT: 3,
  CASE_TRANSFER_REJECT: 3,
  SETTLEMENT_ACCEPT: 3,
  SETTLEMENT_REJECT: 3,
  SUMMONS: 3,
  NOTICE: 3,
  BAIL: 3,
  WARRANT: 3,
  PROCLAMATION: 3,
  ATTACHMENT: 3,
  WITHDRAWAL_ACCEPT: 3,
  WITHDRAWAL_REJECT: 3,
  OTHERS: 3,
  APPROVE_VOLUNTARY_SUBMISSIONS: 3,
  REJECT_VOLUNTARY_SUBMISSIONS: 3,
  REJECT_BAIL: 3,
  ACCEPT_BAIL: 3,
  SET_BAIL_TERMS: 3,
  JUDGEMENT: 3,
  CHECKOUT_ACCEPTANCE: 1,
  CHECKOUT_REJECT: 1,
  COST: 3,
  WITNESS_BATTA: 3,
  DRAFT_IN_PROGRESS: 2,
  ABATE_CASE: 3,
  ACCEPT_RESCHEDULING_REQUEST: 3,
  MISCELLANEOUS_PROCESS: 3,
};

/**
 * Time constants
 */
export const dayInMillisecond = 24 * 3600 * 1000;

/**
 * Error keys
 */
export const ErrorAttendeesKey = "attendees";
