export const Urls = {
  Authenticate: "/user/oauth/token",
  orders: {
    orderCreate: "/order/v1/create",
    orderAddItem: "/order/v2/add-item",
    orderManagementAddItem: "/order-management/v2/add-item",
    orderRemoveItem: "/order/v2/remove-item",
    orderUpdate: "/order/v1/update",
    orderSearch: "/order/v1/search",
    orderManagementCreate: "/order-management/v1/_createOrder",
    orderManagementUpdate: "/order-management/v1/_updateOrder",
    taskCreate: "/task/v1/create",
    pendingTask: "/analytics/pending_task/v1/create",
    createHearings: "/hearing/v1/create",
    updateHearings: "/hearing/v1/update",
    getPendingTaskFields: "/inbox/v2/_getFields",
    orderPreviewPdf: "/egov-pdf/order",
    searchTasks: "/task/v1/search",
    orderNotificationSearch: "/inbox/v2/index/_search",
  },
  FileFetchById: "/filestore/v1/files/id",
  Epost: {
    EpostUpdate: "/epost-tracker/epost/v1/_updateEPost",
    EpostReportDownload: "/epost-tracker/epost/v1/download/excel",
  },
  Scheduler: {
    reschedule: "/scheduler/hearing/v1/_reschedule",
  },
  Task: {
    uploadDoc: "/task/v1/uploadDocument",
    updateTask: "/task/v1/update",
    search: "/task/v1/search",
  },
  SBIPayment: {
    payment: "/sbi-backend/payment/v1/_processTransaction",
  },
  orderManagement: {
    getOrdersToSign: "/order-management/v1/_getOrdersToSign",
    updateSignedOrders: "/order-management/v1/_updateSignedOrders",
  },
  digitalizationService: {
    getDigitalizedDocumentsToSign: "/digitalized-documents/v1/_getDigitalizedDocumentsToSign",
    updateSignedDigitalizedDocuments: "/digitalized-documents/v1/_updateSignedDigitalizedDocuments",
  },
  processManagement: {
    getProcessToSign: "/task/v1/_getTasksToSign",
    updateSignedProcess: "/task/v1/_updateSignedTasks",
    bulkSend: "/task/v1/bulk-send",
  },
  openApi: {
    searchOrders: "/openapi/v1/getOrderDetails",
    taskManagementCreate: "/openapi/task-management/v1/_create",
    taskManagementUpdate: "/openapi/task-management/v1/_update",
    taskManagementSearch: "/openapi/task-management/v1/_search",
    summonsPayment: "/openapi/payment/v1/_calculate",
    getTreasuryPaymentBreakup: "/openapi/payment/v1/_getHeadBreakDown",
    fetchBill: "/openapi/payment/v1/_fetchbill",
    eTreasury: "/openapi/payment/v1/_processChallan",
    searchBill: "/openapi/payment/v1/_searchbill",
    billFileStoreId: "/openapi/payment/v1/getPaymentReceipt",
    setCaseUnlock: "/openapi/lock/v1/_release",
    getPaymentLockStatus: "/openapi/lock/v1/_get",
    setCaseLock: "/openapi/lock/v1/_set",
    FileFetchByFileStore: "/openapi/v1/landing_page/file",
    addAddress: "/openapi/v1/case/addAddress",
    offlinePayment: "/openapi/offline-payment/_create",
  },
};
