CREATE TABLE id_generator
(
    id bigserial NOT NULL,
    idname character varying(200) NOT NULL,
    tenantid character varying(200) NOT NULL,
    format character varying(200) NOT NULL,
    sequencenumber  integer NOT NULL,
    
    CONSTRAINT pk_id_generator PRIMARY KEY (id)
);
CREATE SEQUENCE SEQ_ACK_NUM;
CREATE SEQUENCE SEQ_ASSESMNT_NUM;

CREATE SEQUENCE SEQ_COLL_RCPT_NUM;

CREATE SEQUENCE SEQ_UPIC_NUM;

CREATE SEQUENCE SEQ_ULB_CODE;

CREATE SEQUENCE SEQ_TL_NUM;

CREATE SEQUENCE seq_employee_code;
CREATE SEQUENCE SEQ_TL_APP_NUM;

CREATE SEQUENCE SEQ_SWM_TRN_NUM;


CREATE SEQUENCE SEQ_SUMMON_CODE;
CREATE SEQUENCE SEQ_SUMMON_REFERENCE;
CREATE SEQUENCE SEQ_CASE_REFERENCE;
CREATE SEQUENCE SEQ_ADVOCATE_CODE;
CREATE SEQUENCE SEQ_ADVOCATEPAYMENT_CODE;
CREATE SEQUENCE SEQ_OPINION_CODE;

CREATE SEQUENCE SEQ_VOUCHER_CODE;
CREATE SEQUENCE SEQ_CASE_ADVOCATE;
CREATE SEQUENCE SEQ_NOTICE;
CREATE SEQUENCE SEQ_REGISTER;
CREATE SEQUENCE SEQ_PARAWISE_COMMENTS;
CREATE SEQUENCE SEQ_HEARING_DETAILS;
CREATE SEQUENCE SEQ_SWM_CTRT_NUM;
CREATE SEQUENCE SEQ_SWM_VNDR_NUM;
CREATE SEQUENCE SEQ_SWM_CTRTR_NUM;
CREATE SEQUENCE SEQ_SWM_VNDR_CTRT_NUM;
CREATE SEQUENCE SEQ_REFERENCE_EVIDENCE;
CREATE SEQUENCE SEQ_SWM_VS_TRN_NUM;
DROP SEQUENCE SEQ_SWM_CTRTR_NUM;

CREATE SEQUENCE SEQ_SWM_SPLR_NUM;

CREATE SEQUENCE SEQ_SWM_VHL_TRIP_NUM;
CREATE SEQUENCE SEQ_SWM_VENDOR_PAYMENT_NUM;

CREATE SEQUENCE SEQ_SWM_SNTS_TRGT_NUM;

CREATE SEQUENCE SEQ_SWM_STF_TRN_NUM;

CREATE SEQUENCE SEQ_PERSONAL_DETAILS;

CREATE SEQUENCE SEQ_AGENCY;
CREATE SEQUENCE SEQ_EVENT;
CREATE SEQUENCE SEQ_EGF_BILL_DFT_NUM;

CREATE SEQUENCE SEQ_SWM_VMR_TRN_NUM;

CREATE SEQUENCE SEQ_SWM_SHIFT_CODE_NUM;

CREATE SEQUENCE SEQ_EG_PT_ACK;
CREATE SEQUENCE SEQ_EG_PT_ASSM;

CREATE SEQUENCE SEQ_EG_PG_TXN;

CREATE SEQUENCE SEQ_EG_PT_PTID;

CREATE SEQUENCE SEQ_EG_TL_APL;
CREATE SEQUENCE SEQ_EG_PT_LN;


DELETE FROM id_generator WHERE id IN (SELECT id FROM id_generator gen INNER JOIN (SELECT count(*) as count, tenantid, idname FROM id_generator GROUP BY idname, tenantid) gencount 

ON gen.idname = gencount.idname AND gen.tenantid = gencount.tenantid WHERE count > 1);

ALTER TABLE id_generator DROP CONSTRAINT pk_id_generator;

ALTER TABLE id_generator ADD CONSTRAINT pk_id_generator PRIMARY KEY (idname, tenantid);


CREATE SEQUENCE SEQ_EG_HRMS_EMP_CODE;

CREATE SEQUENCE seq_uc_demand_consumer_code;

ALTER TABLE eg_indexer_job ADD COLUMN recordstobeindexed bigint;
ALTER TABLE eg_indexer_job ADD COLUMN totalrecordsindexed bigint;
