openapi: 3.0.0

info:
  title: Bail Management Service
  description: APIs for managing bail bonds and digital signing in DRISTI
  version: 1.0.0

servers:
  - url: /api
    description: Base API path

tags:
  - name: Bails
  - name: Digital Signatures

security:
  - bearerAuth: []

paths:

  /v1/_create:
    post:
      tags: [Bails]
      summary: Create bail bond
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BailRequest'
            example:
              requestInfo:
                apiId: Rainmaker
                authToken: <AUTH_TOKEN>
                msgId: 1730977593273|en_IN
              bail:
                tenantId: kl
                caseId: 2f6fe4ae-352f-420d-b243-679191b4ba01
                bailNumber: KL-BAIL-2024-00012
                bailType: PERSONAL
                status: DRAFT
                amount: 50000
                isActive: true
      responses:
        '201':
          description: Bail created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BailResponse'

  /v1/_update:
    post:
      tags: [Bails]
      summary: Update bail bond
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BailRequest'
      responses:
        '200':
          description: Bail updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BailResponse'

  /v1/_search:
    post:
      tags: [Bails]
      summary: Search bail bonds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BailSearchRequest'
      responses:
        '200':
          description: Bail search result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BailSearchResponse'

  /v1/_getBailsToSign:
    post:
      tags: [Digital Signatures]
      summary: Fetch bails pending digital signature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BailsToSignRequest'
      responses:
        '200':
          description: Bails ready for signing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BailsToSignResponse'

  /v1/_updateSignedBails:
    post:
      tags: [Digital Signatures]
      summary: Update digitally signed bails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSignedBailRequest'
      responses:
        '200':
          description: Signed bails updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSignedBailResponse'

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    BailRequest:
      type: object
      required: [requestInfo, bail]
      properties:
        requestInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo"
        bail:
          $ref: '#/components/schemas/Bail'

    BailResponse:
      type: object
      properties:
        responseInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo"
        bails:
          type: array
          items:
            $ref: '#/components/schemas/Bail'

    BailSearchRequest:
      type: object
      properties:
        requestInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo"
        criteria:
          $ref: '#/components/schemas/BailSearchCriteria'
        pagination:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination"

    BailSearchResponse:
      type: object
      properties:
        responseInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo"
        bails:
          type: array
          items:
            $ref: '#/components/schemas/Bail'
        totalCount:
          type: integer
          example: 1

    UpdateSignedBailRequest:
      type: object
      required: [requestInfo, signedBails]
      properties:
        requestInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo"
        signedBails:
          type: array
          items:
            $ref: '#/components/schemas/SignedBail'

    UpdateSignedBailResponse:
      type: object
      properties:
        responseInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo"
        updatedBailIds:
          type: array
          items:
            type: string
            format: uuid

    BailsToSignRequest:
      type: object
      properties:
        requestInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo"
        bailIds:
          type: array
          items:
            type: string
            format: uuid

    BailsToSignResponse:
      type: object
      properties:
        responseInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo"
        bailList:
          type: array
          items:
            $ref: '#/components/schemas/BailToSign'

    SignedBail:
      type: object
      required: [bailId, signature]
      properties:
        bailId:
          type: string
          format: uuid
        signature:
          type: string
        signedBy:
          type: string
        signedOn:
          type: string
          format: date-time

    BailSearchCriteria:
      type: object
      properties:
        tenantId:
          type: string
        bailNumber:
          type: string
        caseId:
          type: string
          format: uuid
        status:
          type: string

    Bail:
      type: object
      required: [tenantId, caseId, bailNumber, bailType, status]
      properties:
        id:
          type: string
          format: uuid
        tenantId:
          type: string
        caseId:
          type: string
          format: uuid
        bailNumber:
          type: string
        bailType:
          type: string
        status:
          type: string
          enum: [DRAFT, ISSUED, EXECUTED, CANCELLED]
        amount:
          type: number
          format: double
        additionalDetails:
          type: object
        auditDetails:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails"

    BailToSign:
      type: object
      properties:
        bailId:
          type: string
          format: uuid
        bailNumber:
          type: string
        signUrl:
          type: string
          format: uri
        documentType:
          type: string
