openapi: "3.0.0"
info:
  title: All Public/Open APIs supported by the platform
  description: This API specification defines the various APIs that are open to external world. Anyone can call these. These are unauthenticated APIs. These need to managed via rate limiting settings at the gateway level to limit access
  version: 0.1.0
tags:
  - name: Open APIs
paths:
  /openapi/v1/{tenantID}/case/cnr/{cnrNumber}:
    get:
      tags:
        - Open APIs
      summary: get case summary by cnr number
      description: The API is used to get case summary details using the case CNR Number within a specific tenant. 
                  example - GET /openapi/v1/KL/case/cnr/KLKM520008652024
      operationId: getCaseByCNR
      parameters:
        - name: tenantID
          in: path
          description: tenant ID
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z]{2}$"
            maxLength: 2
            minLength: 2
        - name: cnrNumber
          in: path
          description: the CNR number of the case, whose summary is requested
          required: true
          schema:
            type: string
            maxLength: 16
            minLength: 16
      responses:
        '200':
          description: ResponseInfo with case summary
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CaseSummaryResponse'
        '400':
          description: querying case summary failed
          content:
            'application/json':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes

  /openapi/v1/{tenantID}/case/{year}/{caseType}:
    get:
      tags:
        - Open APIs
      summary: get case summary by case number for a specific year
      description: The API is used to get case summary details within a specific tenant. The parameters are year, type of the case (CMP, CC or ST) and the case number. 
          example -  1. GET /openapi/v1/KL/case/2024/CMP/?page=1&size=10&sort=registrationDate,desc
                  -  2. GET /openapi/v1/KL/case/2024/CMP/?caseNumber=CMP/15/2024
      operationId: getCaseByCaseNumber
      parameters:
        - name: tenantID
          in: path
          description: tenant ID
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z]{2}$"
            maxLength: 2
            minLength: 2
        - name: year
          in: path
          description: if type= CMP, then year in which the case was registered. Can check based on registration date also. If type = CC/ST, then check against CourtCase.courtCaseNumber(year). The minimum year is set to 2024 as this is the year the system has gone live and the first case in the system is from 2024. No earlier cases exist.
          required: true
          schema:
            type: integer
            format: int32
            minimum: 2024
        - name: caseType
          in: path
          description: the type of the case CMP/CC/ST
          required: true
          schema:
            type: string
            enum: [CMP, CC, ST]
        - name: caseNumber
          in: query
          description: the case number (CMP or ST) of the case, whose summary is requested. This optional parameter. If not specified, system will return all CMP/CC/ST cases for the specified tenant and year
          required: false
          schema:
            type: string
            maxLength: 18
            minLength: 9
        - name: offset
          in: query
          description: Page number to retrieve (0-based index)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
        - name: sort
          in: query
          description: Sorting criteria in the format `field,asc` or `field,desc`
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ResponseInfo with case summary
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CaseListSummaryResponse'
        '400':
          description: querying case summary failed
          content:
            'application/json':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes

components:
  schemas:
    CaseSummaryResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        caseSummary:
          $ref: '#/components/schemas/CaseSummary'

    CaseListSummaryResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        caseSummary:
          type: array
          items:
            $ref: '#/components/schemas/CaseSummary'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination

    CaseSummary:
      type: object
      description: this is a summary representation of CourtCase object. A limited set of fields, formatted appropriately are returned. Since the object already exists, there are no field level rules set for this summary object
      properties:
        cnrNumber:
          type: string
          maxLength: 16
          minLength: 16
          example: "KLKM521235562024"
        filingNumber:
          type: string
          maxLength: 14
          minLength: 14
          example: "KL-000075-2024"
        filingDate:
          type: string
          format: date
          description: filing date in YYYY-MM-DD format, in IST time zone
          example: "2024-11-24"
        registrationNumber:
          type: string
          description: CMP number. null is not available
          example: "CMP/1/2024"
          minLength: 10
          maxLength: 18
        registrationDate:
          type: string
          format: date
          description: registration date in YYYY-MM-DD format, in IST time zone
          example: "2024-11-24"
        caseType:
          type: string
          example: "Summary Trail"
          minLength: 5
          maxLength: 20
        statutesAndSections:
          type: array
          items:
            type: object
            properties:
              statute:
                type: string
                example: "NIA"
              sections:
                type: array
                items:
                  type: string
                example: ["S138", "S142(1)(a)", "S145"]
          description: An array of statute and sections for the case
        subStage:
          type: string
          description: this will be returned as "<stage> - <sub stage>"
          example: "Pre-Trail - Appearance"
        judgeName:
          type: string
          description: full name of the Judge
        complainant:
          type: string
          description: full name of the primary complainant
        respondent:
          type: string
          description: full name of the primary respondent
        advocateComplainant:
          type: string
          description: full name of the primary advocate of complainant
        advocateRespondent:
          type: string
          description: full name of the primary advocate of respondent
