openapi: 3.0.0

info:
  title: Order Management Service
  description: APIs to manage court orders in DRISTI
  version: 1.0.0

servers:
  - url: /order-services
    description: Order Service Base Path

tags:
  - name: Orders
    description: APIs for managing court orders

security:
  - bearerAuth: []

paths:

  /v1/_create:
    post:
      tags: [Orders]
      summary: Create a new court order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
            example:
              requestInfo:
                apiId: Rainmaker
                authToken: <AUTH_TOKEN>
                msgId: 1730977593273|en_IN
              order:
                tenantId: kl
                filingNumber: KL-000105-2024
                cnrNumber: KLKM520001742024
                hearingNumber: KL-000105-2024-HR1
                orderType: SUMMONS
                status: DRAFT_IN_PROGRESS
                isActive: true
                createdDate: 1730794124145
                additionalDetails:
                  isReIssueSummons: true
      responses:
        '201':
          description: Order successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'

  /v1/_update:
    post:
      tags: [Orders]
      summary: Update an existing order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
            example:
              requestInfo:
                apiId: Rainmaker
                authToken: <AUTH_TOKEN>
              order:
                id: 03cbbf4d-42ac-4c99-8bba-2e548a7d2f18
                status: ISSUED
                isActive: true
      responses:
        '200':
          description: Order successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'

  /v1/_search:
    post:
      tags: [Orders]
      summary: Search orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderSearchRequest'
            example:
              requestInfo:
                apiId: Rainmaker
                authToken: <AUTH_TOKEN>
                msgId: 1730970507148|en_IN
              criteria:
                tenantId: kl
                filingNumber: KL-000105-2024
              pagination:
                limit: 10
                offset: 0
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'

  /v1/_exists:
    post:
      tags: [Orders]
      summary: Check order existence
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderExistsRequest'
            example:
              requestInfo:
                apiId: Rainmaker
                authToken: <AUTH_TOKEN>
              orderIds:
                - 03cbbf4d-42ac-4c99-8bba-2e548a7d2f18
      responses:
        '200':
          description: Existence check response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderExistsResponse'

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    OrderRequest:
      type: object
      required: [requestInfo, order]
      properties:
        requestInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo"
        order:
          $ref: '#/components/schemas/Order'

    OrderResponse:
      type: object
      properties:
        responseInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo"
        order:
          $ref: '#/components/schemas/Order'

    Order:
      type: object
      description: Court order entity
      required: [tenantId, orderType, status, isActive, createdDate]
      properties:
        id:
          type: string
          format: uuid
          example: 03cbbf4d-42ac-4c99-8bba-2e548a7d2f18
        tenantId:
          type: string
          example: kl
        filingNumber:
          type: string
        cnrNumber:
          type: string
        hearingNumber:
          type: string
        orderNumber:
          type: string
          example: KL-000105-2024-OR3
        orderType:
          type: string
          example: SUMMONS
        status:
          type: string
          example: DRAFT_IN_PROGRESS
        isActive:
          type: boolean
        createdDate:
          type: integer
          format: int64
        additionalDetails:
          type: object
        auditDetails:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails"

    OrderSearchRequest:
      type: object
      required: [requestInfo, criteria]
      properties:
        requestInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo"
        criteria:
          $ref: '#/components/schemas/OrderSearchCriteria'
        pagination:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination"

    OrderSearchCriteria:
      type: object
      properties:
        tenantId:
          type: string
        filingNumber:
          type: string
        orderNumber:
          type: string
        status:
          type: string

    OrderListResponse:
      type: object
      properties:
        responseInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo"
        list:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        totalCount:
          type: integer

    OrderExistsRequest:
      type: object
      required: [requestInfo, orderIds]
      properties:
        requestInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo"
        orderIds:
          type: array
          items:
            type: string
            format: uuid

    OrderExistsResponse:
      type: object
      properties:
        responseInfo:
          $ref: "https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo"
        orders:
          type: array
          items:
            type: object
            properties:
              orderId:
                type: string
                format: uuid
              exists:
                type: boolean
