export const STATUS_TYPES = {
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  IN_PROGRESS: "IN_PROGRESS",
};

export const USER_ROLES = {
  CITIZEN: "CITIZEN",
  JUDGE: "JUDGE",
  ADVOCATE: "ADVOCATE",
  EMPLOYEE: "EMPLOYEE",
  STAFF: "STAFF",
};

export const ACTIONS = {
  APPROVE: "APPROVE",
  REJECT: "REJECT",
  SEND_BACK: "SEND_BACK",
  SUBMIT: "SUBMIT",
};
