export const reviewCaseFileFormConfig = [
  {
    body: [
      {
        type: "component",
        component: "SelectReviewAccordion",
        key: "litigentDetails",
        label: "CS_LITIGENT_DETAILS",
        number: 1,
        withoutLabel: true,
        textAreaMaxLength: "255",
        populators: {
          inputs: [
            {
              key: "complainantDetails",
              name: "complainantDetails",
              label: "CS_COMPLAINT_DETAILS",
              icon: "ComplainantDetailsIcon",
              disableScrutiny: true,
              config: [
                {
                  type: "title",
                  value: ["firstName", "middleName", "lastName"],
                  badgeType: "complainantType.name",
                  enableScrutinyField: true,
                },
                {
                  type: "phonenumber",
                  label: "PHONE_NUMBER",
                  value: "complainantVerification.mobileNumber",
                },
                {
                  type: "text",
                  label: "AGE",
                  value: "complainantAge",
                  enableScrutinyField: true,
                },
                {
                  type: "text",
                  label: "DESIGNATION",
                  dependentOn: "complainantType.code",
                  dependentValue: "REPRESENTATIVE",
                  value: "complainantDesignation",
                  enableScrutinyField: true,
                },
                {
                  type: "image",
                  label: "CS_ID_PROOF",
                  value: ["complainantVerification.individualDetails.document", "companyDetailsUpload.document"],
                  enableScrutinyField: true,
                },
                {
                  type: "address",
                  label: "ADDRESS",
                  dependentOn: "complainantType.code",
                  dependentValue: "INDIVIDUAL",
                  value: "addressDetails",
                  enableScrutinyField: true,
                },
                {
                  type: "address",
                  label: "CURRENT_ADDRESS",
                  value: "currentAddressDetails",
                  dependentOn: "complainantType.code",
                  dependentValue: "INDIVIDUAL",
                  enableScrutinyField: true,
                },
                {
                  type: "text",
                  label: "TYPE_OF_ENTITY",
                  dependentOn: "complainantType.code",
                  dependentValue: "REPRESENTATIVE",
                  value: "complainantTypeOfEntity.name",
                  isLocalizationRequired: true,
                  enableScrutinyField: true,
                },
                {
                  type: "text",
                  label: "company_Name",
                  dependentOn: "complainantType.code",
                  dependentValue: "REPRESENTATIVE",
                  value: "complainantCompanyName",
                  enableScrutinyField: true,
                },
                {
                  type: "address",
                  label: "COMPANY_ADDRESS",
                  dependentOn: "complainantType.code",
                  dependentValue: "REPRESENTATIVE",
                  value: "addressCompanyDetails",
                  enableScrutinyField: true,
                },
                {
                  type: "text",
                  label: "HAS_LITIGANT_TRANFERRED_POA_TO_SOMEONE",
                  value: "transferredPOA.name",
                  enableScrutinyField: true,
                  isLocalizationRequired: true,
                },
                {
                  type: "textTitle",
                  label: "POA_HOLDER_NAME",
                  value: ["poaFirstName", "poaMiddleName", "poaLastName"],
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                  enableScrutinyField: true,
                },
                {
                  type: "phonenumber",
                  label: "CS_POA_MOBILE_NUMBER",
                  value: "poaVerification.mobileNumber",
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                },
                {
                  type: "text",
                  label: "CS_POA_AGE",
                  value: "poaAge",
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                  enableScrutinyField: true,
                },
                {
                  type: "image",
                  label: "CS_POA_ID_PROOF",
                  value: ["poaVerification.individualDetails.document"],
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                  enableScrutinyField: true,
                },
                {
                  type: "address",
                  label: "CS_POA_ADDRESS",
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                  value: "poaAddressDetails",
                  enableScrutinyField: true,
                },
                {
                  type: "image",
                  label: "POA_AUTHORIZATION_DOCUMENT",
                  value: ["poaAuthorizationDocument.poaDocument"],
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                  enableScrutinyField: true,
                },
              ],
              data: {},
            },
            {
              key: "respondentDetails",
              name: "respondentDetails",
              label: "CS_RESPONDENT_DETAILS",
              icon: "RespondentDetailsIcon",
              config: [
                {
                  type: "title",
                  value: ["respondentFirstName", "respondentMiddleName", "respondentLastName"],
                  badgeType: "respondentType.name",
                },
                {
                  type: "phonenumber",
                  label: "PHONE_NUMBER",
                  value: "phonenumbers.mobileNumber",
                },
                {
                  type: "text",
                  label: "AGE",
                  value: "respondentAge",
                },
                {
                  type: "text",
                  label: "DESIGNATION",
                  dependentOn: "respondentType.code",
                  dependentValue: "REPRESENTATIVE",
                  value: "respondentDesignation",
                },
                {
                  type: "text",
                  label: "CS_EMAIL_ID",
                  value: "emails.emailId",
                },
                {
                  type: "address",
                  label: "ADDRESS",
                  dependentOn: "respondentType.code",
                  dependentValue: "INDIVIDUAL",
                  value: "addressDetails",
                },
                {
                  type: "text",
                  label: "TYPE_OF_ENTITY",
                  dependentOn: "respondentType.code",
                  dependentValue: "REPRESENTATIVE",
                  value: "respondentTypeOfEntity.name",
                  isLocalizationRequired: true,
                },
                {
                  type: "text",
                  label: "company_Name",
                  dependentOn: "respondentType.code",
                  dependentValue: "REPRESENTATIVE",
                  value: "respondentCompanyName",
                },
                {
                  type: "address",
                  label: "COMPANY_ADDRESS",
                  dependentOn: "respondentType.code",
                  dependentValue: "REPRESENTATIVE",
                  value: "addressDetails",
                },
                {
                  type: "image",
                  label: "CS_DOCUMENT",
                  value: ["companyDetailsUpload.document", "inquiryAffidavitFileUpload.document"],
                },
                {
                  type: "text",
                  label: "HAS_LITIGANT_TRANFERRED_POA_TO_SOMEONE",
                  value: "transferredPOA.name",
                  isLocalizationRequired: true,
                  defaultValue: "NO",
                  hideOnStatus: ["DRAFT_IN_PROGRESS", "CASE_REASSIGNED", "UNDER_SCRUTINY", "PENDING_PAYMENT", "PENDING_REGISTRATION"],
                },
                {
                  type: "textTitle",
                  label: "POA_HOLDER_NAME",
                  value: ["poaFirstName", "poaMiddleName", "poaLastName"],
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                },
                {
                  type: "phonenumber",
                  label: "CS_POA_MOBILE_NUMBER",
                  value: "poaVerification.mobileNumber",
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                },
                {
                  type: "text",
                  label: "CS_POA_AGE",
                  value: "poaAge",
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                },
                {
                  type: "image",
                  label: "CS_POA_ID_PROOF",
                  value: ["poaVerification.individualDetails.document"],
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                },
                {
                  type: "address",
                  label: "CS_POA_ADDRESS",
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                  value: "poaAddressDetails",
                },
                {
                  type: "image",
                  label: "POA_AUTHORIZATION_DOCUMENT",
                  value: ["poaAuthorizationDocument.poaDocument"],
                  dependentOn: "transferredPOA.code",
                  dependentValue: "YES",
                },
              ],
              data: {},
            },
          ],
        },
      },
      {
        type: "component",
        component: "SelectReviewAccordion",
        key: "caseSpecificDetails",
        label: "CS_CASE_SPECIFIC_DETAILS",
        number: 2,
        withoutLabel: true,
        populators: {
          inputs: [
            {
              key: "chequeDetails",
              name: "chequeDetails",
              label: "CS_CHECKQUE_DETAILS",
              icon: "ChequeDetailsIcon",
              config: [
                {
                  type: "title",
                  label: "CS_CHEQUE_NO",
                  value: ["chequeNumber"],
                },
                {
                  type: "text",
                  label: "CS_DISHONOURED_CHEQUE_SIGNATORY_NAME",
                  value: "chequeSignatoryName",
                },
                {
                  type: "text",
                  label: "CS_NAME_ON_CHEQUE",
                  value: "name",
                },
                {
                  type: "text",
                  label: "CS_PAYEE_BANK_NAME",
                  value: "payeeBankName",
                },
                {
                  type: "text",
                  label: "CS_PAYEE_BRANCH_NAME",
                  value: "payeeBranchName",
                },
                {
                  type: "date",
                  label: "CS_DATE_OF_ISSUANCE",
                  value: "issuanceDate",
                  dependentFields: [
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "depositDate" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfDispatch" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfService" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfReply" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfAccrual" },
                  ],
                },
                {
                  type: "text",
                  label: "CS_PAYER_BANK_NAME",
                  value: "payerBankName",
                },
                {
                  type: "text",
                  label: "CS_PAYER_BRANCH_NAME",
                  value: "payerBranchName",
                },
                {
                  type: "text",
                  label: "CS_IFSC_CODE",
                  value: "ifsc",
                },
                {
                  type: "amount",
                  label: "CS_CHEQUE_AMOUNT",
                  value: "chequeAmount",
                },
                {
                  type: "text",
                  label: "POLICE_STATION_JURISDICTION_CHEQUE",
                  value: "policeStationJurisDictionCheque.name",
                  isLocalizationRequired: true,
                },
                {
                  type: "date",
                  label: "CS_DATE_OF_CHEQUE_DEPOSIT",
                  value: "depositDate",
                  dependentFields: [
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "issuanceDate" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfDispatch" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfService" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfReply" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfAccrual" },
                  ],
                },
                {
                  type: "text",
                  label: "REASON_FOR_RETURN_CHEQUE",
                  value: "delayReason.reasonForReturnCheque",
                },
                {
                  type: "formattedText",
                  label: "CS_CHEQUE_ADDITIONAL_DETAILS",
                  value: "chequeAdditionalDetails.text",
                },
                {
                  type: "infoBox",
                  value: "infoBoxData",
                },
                {
                  type: "image",
                  label: "CS_DOCUMENT",
                  value: ["bouncedChequeFileUpload.document", "depositChequeFileUpload.document", "returnMemoFileUpload.document"],
                },
              ],
              data: {},
            },
            {
              key: "debtLiabilityDetails",
              name: "debtLiabilityDetails",
              label: "CS_DEBT_LIABILITY_DETAILS",
              icon: "DebtLiabilityIcon",
              config: [
                {
                  type: "text",
                  label: "CS_NATURE_DEBT_LIABILITY",
                  value: "liabilityNature",
                },
                {
                  type: "text",
                  label: "CHEQUE_FOR_FULL_OR_PARTIAL_LIABILITY",
                  value: "liabilityType.name",
                  isLocalizationRequired: true,
                },
                {
                  type: "amount",
                  label: "CS_PARIAL_AMOUNT",
                  value: "totalAmount",
                },
                {
                  type: "formattedText",
                  label: "CS_DEBT_ADDITIONAL_DETAILS",
                  value: "additionalDebtLiabilityDetails.text",
                },
                {
                  type: "image",
                  label: "CS_DOCUMENT",
                  value: ["debtLiabilityFileUpload.document"],
                },
              ],
              data: {},
            },
            {
              key: "demandNoticeDetails",
              name: "demandNoticeDetails",
              label: "CS_DEMAND_NOTICE_DETAILS",
              icon: "DemandDetailsNoticeIcon",
              config: [
                // {
                //   type: "text",
                //   label: "CS_MODE_OF_DISPATCH",
                //   value: "modeOfDispatchType.modeOfDispatchType.name",
                // },
                {
                  type: "infoBox",
                  value: "infoBoxData",
                },
                {
                  type: "date",
                  label: "CS_DATE_OF_DISPATCH_LDN",
                  value: "dateOfDispatch",
                  dependentFields: [
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "depositDate" },
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "issuanceDate" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfService" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfReply" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfAccrual" },
                  ],
                },
                {
                  type: "date",
                  label: "CS_DATE_OF_SERVICE_LDN",
                  value: "dateOfService",
                  dependentFields: [
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "depositDate" },
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "issuanceDate" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfDispatch" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfReply" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfAccrual" },
                  ],
                },
                {
                  type: "date",
                  label: "CS_DATE_OF_REPLY_LDN",
                  value: "dateOfReply",
                  notAvailable: "NO_REPLY_RECIEVED",
                  dependentFields: [
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "depositDate" },
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "issuanceDate" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfDispatch" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfService" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfAccrual" },
                  ],
                },
                {
                  type: "date",
                  label: "CS_DATE_OF_ACCRUAL_LDN",
                  value: "dateOfAccrual",
                  dependentFields: [
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "depositDate" },
                    { configKey: "caseSpecificDetails", page: "chequeDetails", field: "issuanceDate" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfDispatch" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfService" },
                    { configKey: "caseSpecificDetails", page: "demandNoticeDetails", field: "dateOfReply" },
                  ],
                },
                {
                  type: "image",
                  label: "CS_DOCUMENT",
                  value: [
                    "legalDemandNoticeFileUpload.document",
                    "proofOfDispatchFileUpload.document",
                    "proofOfAcknowledgmentFileUpload.document",
                    "proofOfReplyFileUpload.document",
                  ],
                },
              ],
              data: {},
            },
            {
              key: "delayApplications",
              name: "delayApplications",
              label: "CS_DELAY_CONDONATION_APPLICATION",
              icon: "DemandDetailsNoticeIcon",
              config: [
                {
                  type: "text",
                  label: "CS_QUESTION_DELAY_APPLICATION",
                  value: "delayCondonationType.name",
                  isLocalizationRequired: true,
                },
                // {
                //   type: "text",
                //   label: "CS_TEXTAREA_HEADER_DELAY_REASON",
                //   value: "delayApplicationReason.reasonForDelay",
                // },
                {
                  type: "text",
                  label: "SKIP_DELAY_APPLICATION_CONFIRM",
                  value: "isDcaSkippedInEFiling.name",
                  dependentOn: "delayCondonationType.name",
                  dependentValue: "NO",
                  isLocalizationRequired: true,
                },
                {
                  type: "formattedText",
                  label: "DELAY_ADDITIONAL_INFO",
                  value: "additionalDelayCondonationDetails.text",
                },
                {
                  type: "image",
                  label: "CS_DOCUMENT",
                  value: ["condonationFileUpload.document"],
                  dependentOn: "delayCondonationType.name",
                  dependentValue: "NO",
                },
              ],
              data: {},
            },
          ],
        },
      },
      {
        type: "component",
        component: "SelectReviewAccordion",
        key: "additionalDetails",
        label: "CS_ADDITIONAL_DETAILS",
        number: 3,
        withoutLabel: true,
        populators: {
          inputs: [
            {
              key: "witnessDetails",
              name: "witnessDetails",
              label: "CS_WITNESS_DETAIL_HEADING",
              icon: "WitnessDetailsIcon",
              noDataText: "NO_WITNESSES_ADDED",
              config: [
                {
                  type: "witnessTitle",
                  value: ["firstName", "middleName", "lastName", "witnessDesignation"],
                },
                {
                  type: "phonenumber",
                  label: "PHONE_NUMBER",
                  value: "phonenumbers.mobileNumber",
                },
                {
                  type: "text",
                  label: "CS_EMAIL_ID",
                  value: "emails.emailId",
                },
                {
                  type: "text",
                  label: "AGE",
                  value: "witnessAge",
                },
                {
                  type: "address",
                  label: "ADDRESS",
                  value: "addressDetails",
                },
                {
                  type: "formattedText",
                  label: "CS_TEXTAREA_WITNESS_ADDITIONAL_DETAIL",
                  value: "witnessAdditionalDetails.text",
                },
              ],
              data: {},
            },
            {
              key: "prayerSwornStatement",
              name: "prayerSwornStatement",
              label: "CS_PRAYER_AND_SWORN_STATEMENT_HEADING",
              icon: "PrayerSwornIcon",
              config: [
                // {
                //   type: "infoBox",
                //   value: "infoBoxData",
                // },
                // {
                //   type: "text",
                //   label: "CS_CASE_SETTLEMENT_CONDITION_SUBHEADER",
                //   value: "caseSettlementCondition.text",
                // },
                {
                  type: "formattedText",
                  label: "CS_MEMORANDUM_OF_COMPLAINT_HEADER",
                  // textDependentOn: "memorandumOfComplaint.document",
                  // textDependentValue: "DOCUMENT_UPLOADED",
                  value: "memorandumOfComplaint.text",
                },
                // {
                //   type: "text",
                //   label: "CS_PRAYER_FOR_RELIEF_HEADER",
                //   textDependentOn: "prayerForRelief.document",
                //   textDependentValue: "DOCUMENT_UPLOADED",
                //   value: "prayerForRelief.text",
                // },
                {
                  type: "text",
                  label: "CS_SWORN_STATEMENT_HEADER",
                  textDependentOn: "swornStatement.document",
                  textDependentValue: "DOCUMENT_UPLOADED",
                  value: "swornStatement.text",
                },
                {
                  type: "formattedText",
                  label: "CS_PRAYER",
                  value: "prayer.text",
                },
                {
                  type: "formattedText",
                  label: "CS_ADDITIONAL_DETAILS",
                  value: "additionalDetails.text",
                },
                // {
                //   type: "text",
                //   label: "CS_SWORN_PAGE_ADDITIONAL_ACTS_SECTIONS_HEADER",
                //   value: "additionalActsSections.text",
                // },
                {
                  type: "image",
                  label: "CS_DOCUMENT",
                  value: ["swornStatement.document", "SelectUploadDocWithName"],
                },
              ],
              data: {},
            },
            {
              key: "advocateDetails",
              name: "advocateDetails",
              label: "CS_ADVOCATE_DETAILS",
              icon: "AdvocateDetailsIcon",
              disableScrutiny: true,
              config: [
                {
                  type: "title",
                  prefix: "Complainant:",
                  value: [
                    "multipleAdvocatesAndPip.boxComplainant.firstName",
                    "multipleAdvocatesAndPip.boxComplainant.middleName",
                    "multipleAdvocatesAndPip.boxComplainant.lastName",
                  ],
                },
              ],
              data: {},
            },
          ],
        },
      },
      {
        type: "component",
        component: "SelectReviewAccordion",
        key: "submissionFromAccused",
        label: "CS_SUBMISSSIONS_FROM_ACCUSED",
        number: 4,
        withoutLabel: true,
        populators: {
          inputs: [
            {
              key: "submissionFromAccused",
              name: "submissionFromAccused",
              label: "CS_SUBMISSSIONS_FROM_ACCUSED",
              icon: "WitnessDetailsIcon",
              config: [
                {
                  type: "infoBox",
                  value: "infoBoxData",
                },
                {
                  type: "image",
                  label: "CS_DOCUMENT",
                  value: ["vakalatnamaDocument", "responseDocuments", "pipAffidavitDocument", "supportingDocument"],
                },
              ],
              data: {},
            },
          ],
        },
      },
      {
        key: "scrutinyMessage",
        type: "component",
        withoutLabel: true,
        component: "SelectEmptyComponent",
        populators: {},
      },
    ],
  },
];

export const reviewcasefileconfig = {
  formconfig: reviewCaseFileFormConfig,
  header: "CS_REVIEW_CASE_FILE_HEADING",
  subtext: "CS_REVIEW_CASE_FILE_SUBTEXT",
  className: "review-case-file",
};
