CREATE TABLE njdg_transform_record (
    cino VARCHAR(50) NOT NULL,
    date_of_filing VARCHAR(50),
    dt_regis VARCHAR(50),
    case_type VARCHAR(50),
    fil_no VARCHAR(50),
    fil_year VARCHAR(10),
    reg_no VARCHAR(50),
    reg_year VARCHAR(10),
    date_first_list VARCHAR(50),
    date_next_list VARCHAR(50),
    pend_disp VARCHAR(5),
    date_of_decision VARCHAR(50),
    disp_reason TEXT,
    disp_nature TEXT,
    desgname VARCHAR(200),
    court_no VARCHAR(20),
    est_code VARCHAR(20),
    state_code VARCHAR(20),
    dist_code VARCHAR(20),
    purpose_code VARCHAR(50),
    pet_name TEXT,
    pet_adv TEXT,
    pet_adv_cd TEXT,
    res_name TEXT,
    res_adv TEXT,
    res_adv_cd TEXT,
    pet_adv_bar_reg TEXT,
    res_adv_bar_reg TEXT,
    police_st_code VARCHAR(50),
    police_ncode VARCHAR(50),
    fir_no VARCHAR(50),
    police_station TEXT,
    fir_year VARCHAR(10),
    date_last_list DATE,
    main_matter_cino VARCHAR(50),

    pet_extra_party JSONB CHECK (jsonb_typeof(pet_extra_party) = 'array'),
    res_extra_party JSONB CHECK (jsonb_typeof(res_extra_party) = 'array'),

    pet_age VARCHAR(10),
    res_age VARCHAR(10),
    pet_address TEXT,
    res_address TEXT,
    jocode VARCHAR(50),
    cicri_type VARCHAR(50),

    act JSONB CHECK (jsonb_typeof(act) = 'array'),
    historyofcasehearing JSONB CHECK (jsonb_typeof(historyofcasehearing) = 'array'),
    interimorder JSONB CHECK (jsonb_typeof(interimorder) = 'array'),
    iafiling JSONB CHECK (jsonb_typeof(iafiling) = 'array'),
);