name: pdf-service Image Build workflow
on:
  push:
    branches:
      - develop
      - main
      - release**
    tags:
      - 'v*'
    paths:
      - "common/pdf-service/**"
  pull_request:
    branches:
      - develop
      - uat
      - release
    paths:
      - "common/pdf-service/**"
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    if: (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v'))) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and analyze for Pdf Service
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner -Dsonar.projectKey=solutions_pdf_service -Dsonar.organization=solutions -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.sources=src -Dsonar.exclusions="node_modules/**,dist/**"
        working-directory: common/pdf-service
      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io
      - name: Set Version from Tag or Branch
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}  # Use tag name for version
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Use branch name as version, replacing '/' with '-'
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION=$(echo "${VERSION}" | sed 's|/|-|g')
          else
            VERSION="latest"  # Default version if not a tag or branch
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Git commit_hash for service
        run: |
          commit_hash=$(git log -1 --pretty=format:%H -- common/pdf-service)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Build and Push Docker image for pdf-service
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/pdf-service:${{ env.VERSION }}-${{ env.commit_hash }} -f Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pdf-service:${{ env.VERSION }}-${{ env.commit_hash }}
        working-directory: common/pdf-service
      - name: Build and Push Docker image for pdf-service DB
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/pdf-service-db:${{ env.VERSION }}-${{ env.commit_hash }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pdf-service-db:${{ env.VERSION }}-${{ env.commit_hash }}
        working-directory: common/pdf-service/migration