name: OCR-svc Image Build workflow
on:
  push:
    branches:
      - develop
    paths:
      - 'backend/ocr-service/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'backend/ocr-service/**'
  workflow_dispatch:
  workflow_call:
permissions:
  security-events: write
  contents: read
jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'ocr-service'
          path: 'backend/ocr-service'
          format: 'SARIF'
      - name: Upload SARIF result to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif
        if: always()
      - name: Build and analyze for scheduler-svc
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -f backend/ocr-service/pom.xml package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=solutions_scheduler_svc -Dsonar.organization=solutions -Dsonar.host.url=https://sonarcloud.io/

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Build and Push Docker image for Scheduler-svc
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: |
          docker build --build-arg WORK_DIR="backend/ocr-service" -t ucarsolutionsdev.azurecr.io/pucar_ocr_svc:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker push ucarsolutionsdev.azurecr.io/pucar_ocr_svc:v1.0.0-${{ github.sha }}

      - name: Build and Push Docker image for scheduler-svc_DB
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/pucar_ocr_svc_db:v1.0.0-${{ github.sha }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_ocr_svc_db:v1.0.0-${{ github.sha }}
        working-directory: backend/ocr-service/src/main/resources/db

  Workflow_Trigger:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Trigger Deployment Pipeline for Solutions Dev
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-dev.yaml/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'