name: dristi-case-pdf Image Build workflow
on:
  push:
    branches:
      - develop
      - uat-v0.3
      - dpg-qa-deployment
    paths:
      - 'backend/dristi-case-pdf/**'
  pull_request:
    branches:
      - develop
      - uat-v0.3
      - dpg-qa-deployment
    paths:
      - 'backend/dristi-case-pdf/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/uat-v0.3' || github.ref == 'refs/heads/dpg-qa-deployment')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io
      - name: Git commit_hash for service
        run: |
          commit_hash=$(git log -1 --pretty=format:%H -- backend/dristi-case-pdf)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Build and Push Docker image for dristi-case-pdf
        run: |
          docker build --build-arg WORK_DIR="backend/dristi-case-pdf" -t pucarsolutionsdev.azurecr.io/pucar_dristi_case_pdf:v1.0.0-${{ env.commit_hash }} -f backend/dristi-case-pdf/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_dristi_case_pdf:v1.0.0-${{ env.commit_hash }}


  Workflow_Trigger:
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/uat-v0.3' || github.ref == 'refs/heads/dpg-qa-deployment')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Set Workflow File Based on Branch
        id: set_workflow
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "WORKFLOW_FILE=solutions-dev.yaml" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/uat-v0.3" ]; then
            echo "WORKFLOW_FILE=solutions-qa.yaml" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/dpg-qa-deployment" ]; then
            echo "WORKFLOW_FILE=solutions-dpg-qa.yaml" >> $GITHUB_ENV
          fi

      - name: Trigger Deployment Pipeline
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/${{ env.WORKFLOW_FILE }}/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'