name: sunbirdrc-credential-service Image Build workflow
on:
  push:
    branches:
      - develop
    paths:
      - 'common/sunbirdrc-credential-service/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'common/sunbirdrc-credential-service/**'
  workflow_dispatch:
  workflow_call:
permissions:
  security-events: write
  contents: read
jobs:
  docker_image-build:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'sunbirdrc-credential-service'
          path: 'common/sunbirdrc-credential-service'
          format: 'SARIF'
      - name: Upload SARIF result to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif
        if: always()

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Build and Push Docker image for sunbirdrc-credential-service
        run: |
          docker build --build-arg WORK_DIR="common/sunbirdrc-credential-service" -t pucarsolutionsdev.azurecr.io/sunbirdrc-credential-service:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/sunbirdrc-credential-service:v1.0.0-${{ github.sha }}

      - name: Build and Push Docker image for Advocate_DB
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/sunbirdrc-credential-service-db:v1.0.0-${{ github.sha }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/sunbirdrc-credential-service-db:v1.0.0-${{ github.sha }}
        working-directory: common/sunbirdrc-credential-service/src/main/resources/db

  Workflow_Trigger:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Trigger Deployment Pipeline for Solutions Dev
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-dev.yaml/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'

