name: Dristi-kerala Image Build workflow for QA
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  Intro:
    runs-on: ubuntu-latest
    steps:
      - name: Introduction
        run: echo "Image build for Solutions Started"

  Workflow_Trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Pipeline for Solutions Dev
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-qa.yaml/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'
