name: Synk Security
on:
  push:
    branches:
      - develop
      - main
permissions:
  security-events: write
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version you are using
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Test for Maven Backend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        run: |
          snyk test --all-projects --sarif --debug > snyk-backend.sarif
        working-directory: backend

      - name: Upload SARIF results for Maven Backend
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: backend/snyk-backend.sarif
          category: 'maven-backend'

      - name: Snyk Test for Maven Common
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        run: |
          snyk test --all-projects --sarif --debug > snyk-common.sarif
        working-directory: common

      - name: Upload SARIF results for Maven Common
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: common/snyk-common.sarif
          category: 'maven-common'

      - name: Snyk Test for Frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        run: |
          snyk test --all-projects --sarif --debug > snyk-frontend.sarif
        working-directory: frontend

      - name: Upload SARIF results for Frontend
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: frontend/snyk-frontend.sarif
          category: 'frontend'